services:
  frontend:
    build:
      context: ./frontend-flight-search 
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./BackendFlightSearch
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
