services:
  backend:
    build:
      context: ./BackendFlightSearch
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
  
  frontend:
    build:
      context: ./frontend-flight-search
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
